# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 05:13
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Investigation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat_start', models.FloatField(default=0.0)),
                ('lon_start', models.FloatField(default=0.0)),
                ('lat_end', models.FloatField(default=0.0)),
                ('lon_end', models.FloatField(default=0.0)),
                ('expert_id', models.ImageField(default=0.0, upload_to=b'')),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.DateField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(1, 'status 1'), (2, 'status 2'), (3, 'status 3')], default=1)),
                ('image', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Judgement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.IntegerField(choices=[(1, 'Not Seen'), (2, 'No'), (3, 'Yes')], default=1)),
                ('worker', models.IntegerField(default=0)),
                ('date_completed', models.DateField(blank=True)),
                ('time_completed', models.DateField(blank=True)),
                ('time_duration', models.ImageField(default=0, upload_to=b'')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat_start', models.FloatField(default=0.0)),
                ('lon_start', models.FloatField(default=0.0)),
                ('lat_end', models.FloatField(default=0.0)),
                ('lon_end', models.FloatField(default=0.0)),
                ('investigation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ground_truth.Investigation')),
            ],
        ),
        migrations.CreateModel(
            name='Subregion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat_start', models.FloatField(default=0.0)),
                ('lon_start', models.FloatField(default=0.0)),
                ('lat_end', models.FloatField(default=0.0)),
                ('lon_end', models.FloatField(default=0.0)),
                ('index', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(15), django.core.validators.MinValueValidator(0)])),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ground_truth.Region')),
            ],
        ),
        migrations.AddField(
            model_name='judgement',
            name='subregion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ground_truth.Subregion'),
        ),
    ]
