# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 14:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ground_truth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investigation',
            name='expert_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
