#!/usr/bin/env bash
export DJANGO_SETTINGS_MODULE="geolocate.settings"
export endpoint="https://mturk-requester-sandbox.us-east-1.amazonaws.com"
export HITLayoutId="3XF0Q7N8DQ6JT5RE20OJ3Y1QQEFCQM"
export MAGIC_PASS="groundtruth4theWin"
export HOST="mturk-requester-sandbox.us-east-1.amazonaws.com"
export SECRET_KEY="DFVR3c7/V87YKraAaD3bAzrfZ+mi2oVJBr1MH0Qb"
export HITTypeId="3MEF7FE16LQQHO98QI2ID0G6P4H9A0"
export ACCESS_KEY="AKIAIZFEJZXVEGZKFANQ"
